name: 'CIS_9440_UTA_group_10'
version: '1.0.0'
config-version: 2
# Some default settings for dbt
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

# Set up models, which are basically SQL files, to create tables
models:
 CIS_9440_UTA_group_10:
   +materialized: table

   assignment_work:
     staging:
       +materialized: table
       +schema: staging

     marts:
       +materialized: table
       +schema: marts
      
       shared:
         +materialized: table

       noise:
         +materialized: table

       sale_data:
         +materialized: table

